import { ensureThreeShim } from '../tools/three-shim.mjs';

ensureThreeShim();

const TEST_MODULES = [
  './campaign.test.mjs',
  './heist-campaign.test.mjs',
  './bank-heist-story.test.mjs',
  './combat-core.test.mjs',
  './ground-vehicle.test.mjs',
  './heist-systems.test.mjs',
  './fresh-save-campaign-route.test.mjs',
  './daynight.test.mjs',
  './characters.test.mjs',
  './initiation-canon.test.mjs',
  './initiation-voice.test.mjs',
  './motel-voice.test.mjs',
  './motel-dialogue-timing.test.mjs',
  './apartment-story.test.mjs',
  './apartment-voice-coverage.test.mjs',
  './phone.test.mjs',
  './squatchfather-story.test.mjs',
  './airstrip-story.test.mjs',
  './airstrip-mission.test.mjs',
  './beefrun-lineup.test.mjs',
  './beefrun-runway-start.test.mjs',
  './post-airstrip-story.test.mjs',
  './bada-bing-two-mission.test.mjs',
  './graveyard-controls.test.mjs',
  './gut-presentation.test.mjs',
  './graveyard-mission.test.mjs',
  './hotdog-graveyard-story.test.mjs',
  './hotdog-voice-catalog.test.mjs',
  './scene-audio-residency.test.mjs',
  './bing-dialogue-lock.test.mjs',
  './bing-family.test.mjs',
  './bing-voice-coverage.test.mjs',
  './beefrun-voice-manifest.test.mjs',
  './bing-audio.test.mjs',
  './no-wake-story.test.mjs',
  './silver-story.test.mjs',
  './silver-voice-catalog.test.mjs',
  './squatch-smash-goals.test.mjs',
  './preview-mode.test.mjs',
  './radio-tape.test.mjs',
  './radio-voice-coverage.test.mjs',
  './voice-transition-runtime.test.mjs',
  './sfx-index.test.mjs',
  './audio-production-tools.test.mjs',
  './audio-engine.test.mjs',
  './apartment-audio.test.mjs',
  './inventory.test.mjs',
  './inventory-view.test.mjs',
  './player.test.mjs',
];

for (const modulePath of TEST_MODULES) await import(modulePath);
