import './campaign.test.mjs';
import './characters.test.mjs';
import './apartment-story.test.mjs';
import './phone.test.mjs';
import './squatchfather-story.test.mjs';
import './airstrip-story.test.mjs';
import './airstrip-mission.test.mjs';
import './post-airstrip-story.test.mjs';
import './bada-bing-two-mission.test.mjs';
