import { CHARACTER_IDS } from '../core/campaign.js';
import { getCharacter } from '../core/characters.js';
import { DIALOGUE_PRIORITY } from './dialogue.js';

function line(id, speakerId, text, priority, states, cue = id) {
  const speaker = getCharacter(speakerId);
  return Object.freeze({
    id,
    speakerId,
    subtitleName: speaker?.subtitleName ?? 'Radio',
    text,
    fallbackDuration: Math.max(2.1, text.length / 18),
    recordedDuration: null,
    lookTarget: speakerId,
    gesture: null,
    interruptible: priority < DIALOGUE_PRIORITY.TACTICAL,
    priority,
    states: Object.freeze(states),
    cue: `heist.${cue}`,
  });
}

function npcLine(id, subtitleName, text, priority, states, cue = id) {
  return Object.freeze({
    id,
    speakerId: id.split('_')[0],
    subtitleName,
    text,
    fallbackDuration: Math.max(1.35, text.length / 19),
    recordedDuration: null,
    lookTarget: null,
    gesture: null,
    interruptible: priority < DIALOGUE_PRIORITY.TACTICAL,
    priority,
    states: Object.freeze(states),
    cue: `heist.${cue}`,
  });
}

const P = DIALOGUE_PRIORITY;

export const HEIST_DIALOGUE = Object.freeze({
  crew_snow: line('crew_snow', CHARACTER_IDS.SNOW,
    'Snow. I call the move. You keep the clock honest.', P.BARK, ['CREW_INTRO', 'BRIEFING', 'LOADOUT']),
  crew_rippin: line('crew_rippin', CHARACTER_IDS.RIPPINFLOW,
    'Rippinflow. I drive us in. If the day gets ambitious, you drive us out.', P.BARK, ['CREW_INTRO', 'BRIEFING', 'LOADOUT']),
  crew_shubes: line('crew_shubes', CHARACTER_IDS.SHUBENATOR,
    'Shubenator. Blue case, vault panel, and every wire you do not touch.', P.BARK, ['CREW_INTRO', 'BRIEFING', 'LOADOUT']),
  crew_death: line('crew_death', CHARACTER_IDS.DEATHMEGATRON,
    'DeathMegatron. I move bags and bad ideas out of doorways.', P.BARK, ['CREW_INTRO', 'BRIEFING', 'LOADOUT']),
  crew_numb: line('crew_numb', CHARACTER_IDS.NUMBSKULL,
    'Numbskull. I own the lobby. People calm down when I sound bored.', P.BARK, ['CREW_INTRO', 'BRIEFING', 'LOADOUT']),
  snow_arrival: line('snow_arrival', CHARACTER_IDS.SNOW,
    'Door shut. Phone off. We use names until the masks go on.', P.OBJECTIVE, ['CREW_INTRO']),
  snow_plan: line('snow_plan', CHARACTER_IDS.SNOW,
    'Inside, six people do one job. Outside, six targets move as one.', P.OBJECTIVE, ['BRIEFING']),
  snow_rules: line('snow_rules', CHARACTER_IDS.SNOW,
    'No civilians. No souvenirs. Nobody leaves a person to save a bag.', P.OBJECTIVE, ['BRIEFING']),
  rippin_route: line('rippin_route', CHARACTER_IDS.RIPPINFLOW,
    'Route Green behaves at lunch. Today every light is going to discover a personality.', P.BANTER, ['BRIEFING']),
  shubes_case: line('shubes_case', CHARACTER_IDS.SHUBENATOR,
    'The blue case is organized. Your hands are not part of the organization.', P.BANTER, ['LOADOUT']),
  death_bags: line('death_bags', CHARACTER_IDS.DEATHMEGATRON,
    'Lou bought bigger bags. Apparently confidence has handles.', P.BANTER, ['LOADOUT']),
  numb_alarm: line('numb_alarm', CHARACTER_IDS.NUMBSKULL,
    'I am nowhere near the alarms. This is me saying it before anybody asks.', P.BARK, ['LOADOUT']),
  prospect_ready: line('prospect_ready', CHARACTER_IDS.PROSPECT,
    'Armor is on. Magazines are full. I heard the plan.', P.OBJECTIVE, ['BOARD_VAN']),

  rippin_two_lights: line('rippin_two_lights', CHARACTER_IDS.RIPPINFLOW,
    'Two lights.', P.OBJECTIVE, ['VAN_APPROACH']),
  snow_time: line('snow_time', CHARACTER_IDS.SNOW,
    'Time.', P.OBJECTIVE, ['VAN_APPROACH']),
  shubes_loop: line('shubes_loop', CHARACTER_IDS.SHUBENATOR,
    'Exterior loop is live. It will remain useful until somebody looks out a window.', P.OBJECTIVE, ['MASKS_ON']),
  death_breathe: line('death_breathe', CHARACTER_IDS.DEATHMEGATRON,
    'Breathe now. It costs more in there.', P.BARK, ['MASKS_ON']),

  guard_warning: npcLine('guard_warning', 'Security Guard',
    'Stop right there. Hands where I can see them.', P.TACTICAL, ['BANK_ENTRY']),
  snow_guard: line('snow_guard', CHARACTER_IDS.SNOW,
    'Prospect, visible guard. Put him on the floor.', P.TACTICAL, ['BANK_ENTRY', 'LOBBY_CONTROL']),
  prospect_counterstrike: line('prospect_counterstrike', CHARACTER_IDS.PROSPECT,
    "Good thing about all that Counter-Strike I've been playing.", P.TACTICAL, ['LOBBY_CONTROL']),
  snow_scoreboard: line('snow_scoreboard', CHARACTER_IDS.SNOW,
    'Save the scoreboard. Watch the lobby.', P.OBJECTIVE, ['LOBBY_CONTROL']),
  death_floor: line('death_floor', CHARACTER_IDS.DEATHMEGATRON,
    'Hands clear. Eyes down. Nobody here needs to be brave.', P.TACTICAL, ['LOBBY_CONTROL']),
  civilian_please: npcLine('civilian_please', 'Bank Customer',
    'Nobody move. Please, just do what they say.', P.BARK, ['LOBBY_CONTROL', 'GUARDS_SECURED']),
  numb_manager: line('numb_manager', CHARACTER_IDS.NUMBSKULL,
    'Manager is mine. Teller line is listening.', P.OBJECTIVE, ['GUARDS_SECURED']),
  manager_delay: npcLine('manager_delay', 'Bank Manager',
    'You do not know the delay. That door will not care who is holding the gun.', P.OBJECTIVE, ['MANAGER_ESCORT']),
  shubes_answer: line('shubes_answer', CHARACTER_IDS.SHUBENATOR,
    'He does not have to know it. I know the panel.', P.OBJECTIVE, ['MANAGER_ESCORT']),
  shubes_vault: line('shubes_vault', CHARACTER_IDS.SHUBENATOR,
    'Panel first. Time-delay second. Nobody touches the leads.', P.OBJECTIVE, ['VAULT_BYPASS']),
  snow_clock: line('snow_clock', CHARACTER_IDS.SNOW,
    'Four minutes became two. Fill the bags we have and leave the rest.', P.TACTICAL, ['CASH_LOADING']),
  snow_insured: line('snow_insured', CHARACTER_IDS.SNOW,
    'We came for insured paper, not uninsured people. Keep it clean.', P.BARK, ['CASH_LOADING']),
  numb_signal: line('numb_signal', CHARACTER_IDS.NUMBSKULL,
    'Foot switch. I stopped the teller. I did not stop what she already sent.', P.WARNING, ['ALARM_DISCOVERED', 'EXIT_ORDER']),
  rippin_street: line('rippin_street', CHARACTER_IDS.RIPPINFLOW,
    'Blue lights on both ends. Route Green is turning brown.', P.WARNING, ['ALARM_DISCOVERED', 'EXIT_ORDER']),
  snow_exit: line('snow_exit', CHARACTER_IDS.SNOW,
    'The sirens are the clock now. Bags, tools, people. Move.', P.TACTICAL, ['EXIT_ORDER'], 'snow_exit_alarm'),

  snow_contact: line('snow_contact', CHARACTER_IDS.SNOW,
    'Planters first. Prospect, right side!', P.TACTICAL, ['BANK_DOOR_CONTACT', 'STREET_BLOCK_ONE']),
  death_suppress: line('death_suppress', CHARACTER_IDS.DEATHMEGATRON,
    'Intersection is occupied. I am correcting it.', P.TACTICAL, ['STREET_BLOCK_ONE']),
  rippin_van: line('rippin_van', CHARACTER_IDS.RIPPINFLOW,
    'Van is boxed. Give me five seconds and a miracle with keys.', P.WARNING, ['VAN_REACHED', 'STREET_BLOCK_TWO']),
  rippin_hit: line('rippin_hit', CHARACTER_IDS.RIPPINFLOW,
    'That is my leg. Route Green is officially cancelled.', P.INJURY, ['RIPPIN_INJURED', 'STREET_BLOCK_TWO']),
  snow_fallback: line('snow_fallback', CHARACTER_IDS.SNOW,
    'Mercer garage. Pairs. Leave the van and keep Rippin between us.', P.TACTICAL, ['FALLBACK_ROUTE', 'STREET_BLOCK_TWO']),
  numb_bag: line('numb_bag', CHARACTER_IDS.NUMBSKULL,
    'Bag is down. Rippin is not. Make the choice fast.', P.TACTICAL, ['DROPPED_BAG_DECISION']),
  snow_leave_it: line('snow_leave_it', CHARACTER_IDS.SNOW,
    'Do not trade a person for paper.', P.TACTICAL, ['DROPPED_BAG_DECISION']),
  shubes_garage: line('shubes_garage', CHARACTER_IDS.SHUBENATOR,
    'Sedan is live. The ignition was never the difficult system.', P.OBJECTIVE, ['GARAGE_HOLD']),
  death_load: line('death_load', CHARACTER_IDS.DEATHMEGATRON,
    'Cover me. Bags are heavier when everybody is shooting at the handles.', P.TACTICAL, ['SECONDARY_CAR_LOAD']),

  rippin_drive: line('rippin_drive', CHARACTER_IDS.RIPPINFLOW,
    'Prospect drives. Left out, wrong way on purpose, then the warehouse lights.', P.TACTICAL, ['PLAYER_TAKES_WHEEL']),
  rippin_market_left: line('rippin_market_left', CHARACTER_IDS.RIPPINFLOW,
    'Left at the warehouse. Hold it through Market, then right at the glass tower.', P.TACTICAL, ['CITY_PURSUIT']),
  snow_roadblock: line('snow_roadblock', CHARACTER_IDS.SNOW,
    'Roadblock. Center gap. Do not argue with the cruisers.', P.TACTICAL, ['ROADBLOCK']),
  rippin_canal: line('rippin_canal', CHARACTER_IDS.RIPPINFLOW,
    'Canal road next. Narrow means they cannot put three cars beside us.', P.TACTICAL, ['INDUSTRIAL_ROUTE']),
  shubes_swap: line('shubes_swap', CHARACTER_IDS.SHUBENATOR,
    'Cash first, coats second, weapons in the lined bin. In that order.', P.OBJECTIVE, ['VEHICLE_SWAP']),
  death_swap_bags: line('death_swap_bags', CHARACTER_IDS.DEATHMEGATRON,
    'Eight bags moved. Nobody leaves a handle in the dirty car.', P.OBJECTIVE, ['VEHICLE_SWAP']),
  rippin_swap_aid: line('rippin_swap_aid', CHARACTER_IDS.RIPPINFLOW,
    'Tie it above the tear. I can complain in the clean car.', P.INJURY, ['VEHICLE_SWAP']),

  snow_return: line('snow_return', CHARACTER_IDS.SNOW,
    'Nobody celebrates until I count six people and every bag in this room.', P.OBJECTIVE, ['SAFEHOUSE_RETURN']),
  rippin_aid: line('rippin_aid', CHARACTER_IDS.RIPPINFLOW,
    'The van had one job and chose performance art. Wrap the leg tighter.', P.INJURY, ['FIRST_AID']),
  shubes_defend: line('shubes_defend', CHARACTER_IDS.SHUBENATOR,
    'The vault opened on schedule. The alarm was a separate and inferior system.', P.BARK, ['DEBRIEF']),
  death_ammo: line('death_ammo', CHARACTER_IDS.DEATHMEGATRON,
    'Ammunition accounted for. Everybody else is somebody else’s paperwork.', P.BARK, ['DEBRIEF']),
  numb_home: line('numb_home', CHARACTER_IDS.NUMBSKULL,
    'I saw the tracker late. I saw it. We are still all standing here.', P.BARK, ['DEBRIEF']),
  snow_good: line('snow_good', CHARACTER_IDS.SNOW,
    'You moved when I said move. You covered people before money. Lou will hear that.', P.OBJECTIVE, ['DEBRIEF']),
  lou_call: line('lou_call', CHARACTER_IDS.LOU,
    'Everybody breathing? Good. Clean up. Bada Bing, seven. Wear something worth remembering.', P.OBJECTIVE, ['LOU_CALL_SAFEHOUSE']),
  prospect_home: line('prospect_home', CHARACTER_IDS.PROSPECT,
    'We got out. Everybody came home.', P.OBJECTIVE, ['LOU_CALL_SAFEHOUSE']),
});

export function dialogueLine(id) { return HEIST_DIALOGUE[id] ?? null; }
