#!/usr/bin/env node
/**
 * Everything the game asks for and does not have a recording of.
 *
 *   npm run audio:todo        -> writes VOICE-LINES-TODO.md
 *
 * Two different things end up in here and they are generated differently:
 *
 *   vo.*   a person reading a line. There is no synth fallback for these on
 *          purpose -- a synthesised voice is worse than silence -- so an
 *          unrecorded line is a line that shows as text and says nothing.
 *   the rest
 *          sound effects. These DO have a synth fallback, so an unrecorded
 *          one is audible but crude. Lower priority, still worth having.
 *
 * Written as a file rather than printed because the point of it is to hand it
 * to somebody, and regenerated rather than hand-maintained because a list of
 * outstanding work that has to be remembered to update is a list that is
 * wrong within a week.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));

const have = new Set(read('assets/sfx/index.json').files || []);
const cues = read('assets/sfx/manifest.json').sfx || [];
const missing = cues.filter((c) => !have.has(c.file || `${c.name}.mp3`));

const voice = missing.filter((c) => c.say);
const effects = missing.filter((c) => !c.say);

/** Notes for the person reading, keyed by bank. */
const DIRECTION = {
  'vo.tap': 'Kitchen tap. Flat, to nobody. He turned it on for no reason and knows it.',
  'vo.spooky': 'The comedown. Unbothered, normal volume, the way you talk to an empty room — it stops being funny the second he sounds frightened. He never goes to look.',
  'vo.gun.fire': 'He has just fired a revolver indoors. Not thrilled, not frightened: appalled in a mild, administrative way.',
  'vo.gun.empty': 'The click at the end. Faintly disappointed, as if the gun had let him down.',
  'vo.gun.reload': 'Loading it. He is aware this is a strange thing to be good at.',
  'vo.ammo': 'Finding cartridges in his own flat. Genuine mild surprise.',
  'vo.slice': 'Cold pizza off the coffee table, at whatever time it is. Content.',
  'vo.hr': 'He has just told HR where to go, in writing, having been sacked forty minutes earlier and not yet read that email.',
  'vo.fired': 'Reading that he no longer has a job. Not upset. Processing it the way you process weather.',
};

const bankOf = (name) => name.split('.').slice(0, -1).join('.');

let out = '# Audio still to record — Squatch Life\n\n';
out += `Generated by \`npm run audio:todo\`. ${voice.length} voice line(s), `
  + `${effects.length} effect(s).\n\n`;
out += 'Drop the mp3s in `assets/sfx/` under the filename given, then run '
  + '`npm run sfx:listen` to rebuild `assets/sfx/index.json`.\n\n';

if (voice.length) {
  out += '## Voice\n\nAll in the player voice unless the name says otherwise. These have '
    + '**no fallback** — an unrecorded line shows on screen and plays nothing.\n\n';
  const banks = new Map();
  for (const c of voice) {
    const b = bankOf(c.name);
    if (!banks.has(b)) banks.set(b, []);
    banks.get(b).push(c);
  }
  for (const [bank, list] of banks) {
    out += `### \`${bank}.*\` — ${list.length}\n\n`;
    if (DIRECTION[bank]) out += `${DIRECTION[bank]}\n\n`;
    for (const c of list) out += `${(c.file || `${c.name}.mp3`).padEnd(24)}  ${JSON.stringify(c.say)}\n`;
    out += '\n';
  }
} else {
  out += '## Voice\n\nNothing outstanding. Every written line has a recording.\n\n';
}

if (effects.length) {
  out += '## Effects\n\nThese fall back to the procedural synth, so they are audible '
    + 'already — a recording replaces a rough approximation rather than silence.\n\n';
  for (const c of effects) {
    out += `### \`${c.name}\`${c.duration ? ` — ${c.duration}s` : ''}\n\n`;
    if (c._comment) out += `${c._comment}\n\n`;
    out += `${c.prompt || '(no prompt written)'}\n\n`;
  }
} else {
  out += '## Effects\n\nNothing outstanding.\n\n';
}

fs.writeFileSync(path.join(ROOT, 'VOICE-LINES-TODO.md'), out);
console.log(`VOICE-LINES-TODO.md — ${voice.length} voice, ${effects.length} effects`);
