#!/usr/bin/env node
/**
 * Generate the apartment's sound effects with the ElevenLabs Sound Effects API.
 *
 *   ELEVENLABS_API_KEY=sk_... node tools/generate-sfx.mjs
 *
 * Reads assets/sfx/manifest.json, generates any cue that does not already have
 * an .mp3 next to it, and writes the result into assets/sfx/.
 *
 * Flags:
 *   --force            regenerate cues even if the file already exists
 *   --only <name,...>  generate just these cues
 *   --dry-run          list what would be generated and exit
 *
 * Nothing here is required to play the game: every cue has a procedural
 * WebAudio fallback in src/core/audio.js. This just makes it sound real.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SFX_DIR = path.join(ROOT, 'assets', 'sfx');
const MANIFEST = path.join(SFX_DIR, 'manifest.json');
const ENDPOINT = 'https://api.elevenlabs.io/v1/sound-generation';

const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const valueOf = (f) => {
  const i = args.indexOf(f);
  return i >= 0 ? args[i + 1] : null;
};

const FORCE = has('--force');
const DRY = has('--dry-run');
const ONLY = valueOf('--only')?.split(',').map((s) => s.trim()).filter(Boolean) ?? null;

const API_KEY = process.env.ELEVENLABS_API_KEY || process.env.XI_API_KEY;

async function main() {
  const manifest = JSON.parse(await fs.readFile(MANIFEST, 'utf8'));
  let cues = manifest.sfx || [];
  if (ONLY) cues = cues.filter((c) => ONLY.includes(c.name));

  const pending = [];
  for (const cue of cues) {
    const file = cue.file || `${cue.name}.mp3`;
    const dest = path.join(SFX_DIR, file);
    if (!FORCE && (await exists(dest))) continue;
    pending.push({ cue, dest, file });
  }

  if (!pending.length) {
    console.log(`Nothing to do — all ${cues.length} cues already exist. Use --force to regenerate.`);
    return;
  }

  console.log(`${pending.length} cue(s) to generate:`);
  for (const p of pending) console.log(`  ${p.cue.name.padEnd(20)} ${p.cue.duration ?? 'auto'}s`);

  if (DRY) return;

  if (!API_KEY) {
    console.error(
      '\nELEVENLABS_API_KEY is not set.\n' +
      'Get a key at https://elevenlabs.io, then:\n' +
      '  export ELEVENLABS_API_KEY=sk_...\n' +
      '  npm run sfx\n\n' +
      'The game runs without this — every cue falls back to procedural audio.',
    );
    process.exitCode = 1;
    return;
  }

  await fs.mkdir(SFX_DIR, { recursive: true });

  let ok = 0;
  let failed = 0;
  // Sequential on purpose: friendlier to rate limits, and the log stays readable.
  for (const { cue, dest, file } of pending) {
    process.stdout.write(`  ${cue.name.padEnd(20)} … `);
    try {
      const bytes = await generate(cue);
      await fs.writeFile(dest, bytes);
      console.log(`ok  (${(bytes.length / 1024).toFixed(0)} KB → assets/sfx/${file})`);
      ok++;
    } catch (err) {
      console.log(`FAILED — ${err.message}`);
      failed++;
    }
  }

  await writeIndex();

  console.log(`\nDone. ${ok} generated, ${failed} failed.`);
  if (failed) process.exitCode = 1;
}

/**
 * Record which cue files exist so the game fetches only those. Without this
 * the browser probes for every cue and logs a 404 for each missing one.
 */
async function writeIndex() {
  const entries = await fs.readdir(SFX_DIR);
  const files = [];
  for (const name of entries) {
    if (!/\.(mp3|ogg|wav|m4a)$/i.test(name)) continue;
    const st = await fs.stat(path.join(SFX_DIR, name));
    if (st.size > 512) files.push(name);
  }
  files.sort();
  const indexPath = path.join(SFX_DIR, 'index.json');
  await fs.writeFile(indexPath, JSON.stringify({
    _comment: 'Generated by tools/generate-sfx.mjs. Lists the cue files present in this folder.',
    files,
  }, null, 2) + '\n');
  console.log(`\nWrote assets/sfx/index.json (${files.length} file(s)).`);
}

async function generate(cue) {
  const body = {
    text: cue.prompt,
    model_id: 'eleven_text_to_sound_v2',
    output_format: 'mp3_44100_128',
  };
  if (cue.duration) body.duration_seconds = clamp(cue.duration, 0.5, 30);
  if (cue.loop) body.loop = true;
  if (typeof cue.promptInfluence === 'number') body.prompt_influence = cue.promptInfluence;

  const res = await fetchWithRetry(ENDPOINT, {
    method: 'POST',
    headers: {
      'xi-api-key': API_KEY,
      'content-type': 'application/json',
      accept: 'audio/mpeg',
    },
    body: JSON.stringify(body),
  });

  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 512) throw new Error('response too small to be audio');
  return buf;
}

async function fetchWithRetry(url, options, attempts = 4) {
  let lastError;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, options);
      if (res.ok) return res;
      const text = await res.text().catch(() => '');
      // Rate limited or transient server error: back off and try again.
      if (res.status === 429 || res.status >= 500) {
        lastError = new Error(`HTTP ${res.status} ${text.slice(0, 120)}`);
        await sleep(1000 * 2 ** i);
        continue;
      }
      throw new Error(`HTTP ${res.status} ${text.slice(0, 200)}`);
    } catch (err) {
      lastError = err;
      if (i === attempts - 1) break;
      await sleep(1000 * 2 ** i);
    }
  }
  throw lastError;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));

async function exists(p) {
  try {
    const st = await fs.stat(p);
    return st.size > 512;
  } catch {
    return false;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
