#!/usr/bin/env node
/**
 * Put every authored Cartel Palace line in the sound manifest.
 *
 *   npm run vo:palace          -> synchronize the complete `vo.palace.` bank
 *   npm run check:palace-vo    -> report missing / stale / drifted cues
 *   npm run audio:todo         -> writes the recording handoff markdown
 *
 * ## WHY THIS EXISTS NOW AND NOT BEFORE
 *
 * The finale's forty rows were maintained BY HAND, and
 * `tests/cartel-palace-finale.test.mjs` held them to the script exactly --
 * every cue present, the words identical, the delivery note identical, and no
 * stale rows. That contract is right and it stays. What it did not have was a
 * way to satisfy it: a rewrite of the script meant forty hand edits to a
 * 48,000-line JSON file, which is the drift the test exists to catch being
 * generated by the act of fixing it.
 *
 * The 2026-08-25 rewire -- Mark scrambling, the chef fought alone, Lola and
 * Johnny, three stages of reprisal -- retired or rewrote most of those forty,
 * so the tool got written at the same time as the dialogue. Every other scene
 * in the game already had one (docs/ENGINE-TRAPS.md entry 3: *"a scene with no
 * VO generator is invisible, however much is written for it"*).
 *
 * The Palace used to have a generator for the finale and no canonical owner
 * for the investigation, guard barks, or shift conversations. That made a
 * source correction silently drift away from the recording manifest. All
 * three authored catalogs now feed this one scene generator. The sync replaces
 * rows in place where possible, so repairing three words does not reorder a
 * 48,000-line manifest.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { allFinaleCues, FINALE_SPEAKERS } from '../src/cartel-palace/finale.js';
import { allPalaceConversationLines } from '../src/cartel-palace/conversations.js';
import { allPalaceVoiceLines } from '../src/cartel-palace/voice.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = path.join(ROOT, 'assets/sfx/manifest.json');
const PREFIX = 'vo.palace.';
const FINALE_PREFIX = 'vo.palace.finale.';

const manifestRow = ({ name, voice, say, direction = null }) => {
  const row = { name, voice, say };
  if (direction) row.direction = direction;
  return row;
};

/** Every recordable finale line, in the manifest's own shape. */
export function collectPalaceFinaleCues() {
  return allFinaleCues().map((cue) => manifestRow({
    name: `vo.${cue.cue}.1`, voice: cue.voice, say: cue.text, direction: cue.direction,
  }));
}

/** Every line the Palace runtime can actually request, in manifest shape. */
export function collectPalaceCues() {
  return [
    ...allPalaceVoiceLines().map(manifestRow),
    ...allPalaceConversationLines().map(manifestRow),
    ...collectPalaceFinaleCues(),
  ];
}

/** An updated manifest. Does not mutate or write the input. */
export function syncPalaceFinaleManifest(manifest) {
  const kept = (manifest.sfx || []).filter((cue) => !cue.name.startsWith(FINALE_PREFIX));
  return { ...manifest, sfx: [...kept, ...collectPalaceFinaleCues()] };
}

/** Synchronize the full bank without needlessly moving unchanged rows. */
export function syncPalaceManifest(manifest) {
  const expected = new Map(collectPalaceCues().map((cue) => [cue.name, cue]));
  const seen = new Set();
  const sfx = [];
  for (const cue of manifest.sfx || []) {
    if (!cue.name.startsWith(PREFIX)) {
      sfx.push(cue);
      continue;
    }
    const replacement = expected.get(cue.name);
    if (!replacement || seen.has(cue.name)) continue;
    sfx.push(replacement);
    seen.add(cue.name);
  }
  for (const [name, cue] of expected) if (!seen.has(name)) sfx.push(cue);
  return { ...manifest, sfx };
}

/**
 * Every way the manifest and the script can disagree, named.
 *
 * A MISSING cue is a line nobody will be asked to record; a DRIFTED one is a
 * take of the wrong words, in the wrong voice, or with the wrong delivery note
 * going to the booth; a STALE one is a recording session spent on a line the
 * game no longer says; a DUPLICATE is two entries where the loader takes
 * whichever it saw last.
 */
export function checkPalaceFinaleManifest(manifest) {
  return checkCatalog(manifest, collectPalaceFinaleCues(), FINALE_PREFIX, true);
}

export function checkPalaceManifest(manifest) {
  return checkCatalog(manifest, collectPalaceCues(), PREFIX, false);
}

function checkCatalog(manifest, catalog, prefix, finaleOnly) {
  const failures = [];
  const expected = new Map(catalog.map((cue) => [cue.name, cue]));
  const declared = new Map();
  for (const cue of (manifest.sfx || []).filter((entry) => entry.name.startsWith(prefix))) {
    if (declared.has(cue.name)) failures.push(`duplicate cue ${cue.name}`);
    else declared.set(cue.name, cue);
  }
  for (const [name, cue] of expected) {
    const actual = declared.get(name);
    if (!actual) failures.push(`missing cue ${name}`);
    else if (actual.voice !== cue.voice) failures.push(`drifted voice on ${name}`);
    else if (actual.say !== cue.say) failures.push(`drifted words on ${name}`);
    else if ((actual.direction ?? null) !== (cue.direction ?? null)) {
      failures.push(`drifted delivery note on ${name}`);
    }
  }
  for (const name of declared.keys()) if (!expected.has(name)) failures.push(`stale cue ${name}`);
  /* And the one that is not about the manifest at all: a speaker whose voice
   * profile does not exist produces a cue nobody can cast. */
  const voices = new Set(Object.keys(manifest.voices ?? {}));
  if (voices.size) {
    const wanted = finaleOnly
      ? Object.values(FINALE_SPEAKERS).map(({ name, voice }) => ({ name, voice }))
      : catalog.map(({ name, voice }) => ({ name, voice }));
    for (const speaker of wanted) {
      if (!voices.has(speaker.voice)) {
        failures.push(`${speaker.name} wants voice profile "${speaker.voice}", which the manifest does not have`);
      }
    }
  }
  return failures;
}

function main() {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  if (process.argv.includes('--check')) {
    const failures = checkPalaceManifest(manifest);
    if (failures.length) {
      failures.forEach((failure) => console.error(`FAIL ${failure}`));
      console.error(`${failures.length} Cartel Palace voice problem(s). Run \`npm run vo:palace\`.`);
      process.exitCode = 1;
    } else {
      console.log(`Cartel Palace manifest matches ${collectPalaceCues().length} cue(s).`);
    }
    return;
  }

  const dropped = (manifest.sfx || []).filter((cue) => cue.name.startsWith(PREFIX)).length;
  const cues = collectPalaceCues();
  fs.writeFileSync(MANIFEST, `${JSON.stringify(syncPalaceManifest(manifest), null, 2)}\n`);

  const byWho = {};
  for (const cue of allFinaleCues()) byWho[cue.who] = (byWho[cue.who] ?? 0) + 1;
  console.log(`${cues.length} Cartel Palace voice cue(s) in the manifest`
    + `${dropped ? ` (replaced ${dropped})` : ''}.`);
  for (const [who, count] of Object.entries(byWho).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${(FINALE_SPEAKERS[who]?.name ?? who).padEnd(12)} ${count}`);
  }
  console.log('\nRun `npm run audio:todo` for the recording sheet.');
}

const invoked = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invoked) main();
