#!/usr/bin/env node
/**
 * Put the Cartel Palace's DINING-ROOM confrontation in the sound manifest.
 *
 *   npm run vo:palace          -> synchronize the `vo.palace.finale.` block
 *   npm run check:palace-vo    -> report missing / stale / drifted cues
 *   npm run audio:todo         -> writes the recording handoff markdown
 *
 * ## WHY THIS EXISTS NOW AND NOT BEFORE
 *
 * The finale's forty rows were maintained BY HAND, and
 * `tests/cartel-palace-finale.test.mjs` held them to the script exactly --
 * every cue present, the words identical, the delivery note identical, and no
 * stale rows. That contract is right and it stays. What it did not have was a
 * way to satisfy it: a rewrite of the script meant forty hand edits to a
 * 48,000-line JSON file, which is the drift the test exists to catch being
 * generated by the act of fixing it.
 *
 * The 2026-08-25 rewire -- Mark scrambling, the chef fought alone, Lola and
 * Johnny, three stages of reprisal -- retired or rewrote most of those forty,
 * so the tool got written at the same time as the dialogue. Every other scene
 * in the game already had one (docs/ENGINE-TRAPS.md entry 3: *"a scene with no
 * VO generator is invisible, however much is written for it"*).
 *
 * ## WHAT IT DELIBERATELY DOES NOT OWN
 *
 * The `vo.palace.finale.` prefix, and nothing else. `vo.palace.tony.`,
 * `vo.palace.cleaner.`, `vo.palace.guard.` and `vo.palace.shift.` come from
 * `src/cartel-palace/voice.js` and `conversations.js` and are maintained
 * elsewhere; taking the whole `vo.palace.` prefix here would delete all four
 * banks on the first sync. That is ENGINE-TRAPS entry 4 -- the `heist.` prefix
 * naming both dialogue and effects -- and it is avoided by being narrow.
 *
 * It does not invent cue names either. `allFinaleCues()` produces exactly what
 * `PalaceFinaleDirector` asks the engine for at runtime, so a cue that reaches
 * the booth is a cue the game will actually play.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { allFinaleCues, FINALE_SPEAKERS } from '../src/cartel-palace/finale.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = path.join(ROOT, 'assets/sfx/manifest.json');
const PREFIX = 'vo.palace.finale.';

/** Every recordable finale line, in the manifest's own shape. */
export function collectPalaceFinaleCues() {
  return allFinaleCues().map((cue) => {
    const row = { name: `vo.${cue.cue}.1`, voice: cue.voice, say: cue.text };
    if (cue.direction) row.direction = cue.direction;
    return row;
  });
}

/** An updated manifest. Does not mutate or write the input. */
export function syncPalaceFinaleManifest(manifest) {
  const kept = (manifest.sfx || []).filter((cue) => !cue.name.startsWith(PREFIX));
  return { ...manifest, sfx: [...kept, ...collectPalaceFinaleCues()] };
}

/**
 * Every way the manifest and the script can disagree, named.
 *
 * A MISSING cue is a line nobody will be asked to record; a DRIFTED one is a
 * take of the wrong words, in the wrong voice, or with the wrong delivery note
 * going to the booth; a STALE one is a recording session spent on a line the
 * game no longer says; a DUPLICATE is two entries where the loader takes
 * whichever it saw last.
 */
export function checkPalaceFinaleManifest(manifest) {
  const failures = [];
  const expected = new Map(collectPalaceFinaleCues().map((cue) => [cue.name, cue]));
  const declared = new Map();
  for (const cue of (manifest.sfx || []).filter((entry) => entry.name.startsWith(PREFIX))) {
    if (declared.has(cue.name)) failures.push(`duplicate cue ${cue.name}`);
    else declared.set(cue.name, cue);
  }
  for (const [name, cue] of expected) {
    const actual = declared.get(name);
    if (!actual) failures.push(`missing cue ${name}`);
    else if (actual.voice !== cue.voice) failures.push(`drifted voice on ${name}`);
    else if (actual.say !== cue.say) failures.push(`drifted words on ${name}`);
    else if ((actual.direction ?? null) !== (cue.direction ?? null)) {
      failures.push(`drifted delivery note on ${name}`);
    }
  }
  for (const name of declared.keys()) if (!expected.has(name)) failures.push(`stale cue ${name}`);
  /* And the one that is not about the manifest at all: a speaker whose voice
   * profile does not exist produces a cue nobody can cast. */
  const voices = Object.keys(manifest.voices ?? {});
  if (voices.length) {
    for (const speaker of Object.values(FINALE_SPEAKERS)) {
      if (!voices.includes(speaker.voice)) {
        failures.push(`${speaker.name} wants voice profile "${speaker.voice}", which the manifest does not have`);
      }
    }
  }
  return failures;
}

function main() {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  if (process.argv.includes('--check')) {
    const failures = checkPalaceFinaleManifest(manifest);
    if (failures.length) {
      failures.forEach((failure) => console.error(`FAIL ${failure}`));
      console.error(`${failures.length} Cartel Palace finale voice problem(s). Run \`npm run vo:palace\`.`);
      process.exitCode = 1;
    } else {
      console.log(`Cartel Palace finale manifest matches ${collectPalaceFinaleCues().length} cue(s).`);
    }
    return;
  }

  const dropped = (manifest.sfx || []).filter((cue) => cue.name.startsWith(PREFIX)).length;
  const cues = collectPalaceFinaleCues();
  fs.writeFileSync(MANIFEST, `${JSON.stringify(syncPalaceFinaleManifest(manifest), null, 2)}\n`);

  const byWho = {};
  for (const cue of allFinaleCues()) byWho[cue.who] = (byWho[cue.who] ?? 0) + 1;
  console.log(`${cues.length} Cartel Palace finale voice cue(s) in the manifest`
    + `${dropped ? ` (replaced ${dropped})` : ''}.`);
  for (const [who, count] of Object.entries(byWho).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${(FINALE_SPEAKERS[who]?.name ?? who).padEnd(12)} ${count}`);
  }
  console.log('\nRun `npm run audio:todo` for the recording sheet.');
}

const invoked = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invoked) main();
