#!/usr/bin/env node
/**
 * Take stock of assets/sfx/ after somebody has put files in it.
 *
 * Two outputs, both derived from the folder as it now stands:
 *
 *   index.json    which cue files exist. The game fetches only what this
 *                 lists, so a recording that is not in here is a recording
 *                 the game never plays.
 *   _listen.html  every cue playable inline, grouped by prefix, with the
 *                 prompt or spoken line next to it. Audition the whole set
 *                 without clicking through Explorer.
 *
 *   node tools/sfx-index.mjs
 *
 * This is the command the audio docs send people to after they deliver
 * hand-recorded mp3s, which is why it owns the index and not just the page:
 * it used to write only the page, so a delivered recording landed on disk,
 * never got indexed, never got fetched, and the game went on playing the
 * procedural stand-in with nothing anywhere saying why.
 *
 * ponytail: plain file:// page, no server. `npm start` also serves it.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeIndex } from './sfx-index-json.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SFX_DIR = path.join(ROOT, 'assets', 'sfx');
const AUDITIONS_DIR = path.join(ROOT, 'assets', 'audio', 'auditions');

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

const manifest = JSON.parse(await fs.readFile(path.join(SFX_DIR, 'manifest.json'), 'utf8'));
const byName = new Map((manifest.sfx || []).map((c) => [c.name, c]));

const files = (await fs.readdir(SFX_DIR)).filter((f) => /\.mp3$/i.test(f)).sort();

const groups = new Map();
for (const file of files) {
  const name = file.replace(/\.mp3$/i, '');
  const group = name.startsWith('vo.') ? 'vo' : name.split('.')[0];
  if (!groups.has(group)) groups.set(group, []);
  groups.get(group).push({ file, name, cue: byName.get(name) });
}

const rows = [...groups.entries()].map(([group, items]) => `
  <h2>${esc(group)} <small>${items.length}</small></h2>
  <table>
    ${items.map(({ file, name, cue }) => `
    <tr>
      <td class="n">${esc(name)}</td>
      <td><audio controls preload="none" src="${encodeURIComponent(file)}"></audio></td>
      <td class="d">${esc(cue?.say ? `“${cue.say}”` : cue?.prompt ?? '')}</td>
    </tr>`).join('')}
  </table>`).join('\n');

// Auditions are deliberately kept outside assets/sfx: putting a candidate in
// there makes it part of the fetchable runtime index. List them here instead
// so a reviewer can compare a take without accidentally shipping it.
let auditions = [];
try {
  auditions = (await fs.readdir(AUDITIONS_DIR))
    .filter((file) => /\.(mp3|wav|ogg)$/i.test(file))
    .sort();
} catch (error) {
  if (error?.code !== 'ENOENT') throw error;
}

const auditionRows = auditions.length ? `
  <section class="auditions">
    <h2>auditions <small>${auditions.length} &mdash; candidates only, not live game audio</small></h2>
    <table>
      ${auditions.map((file) => `
      <tr>
        <td class="n">${esc(file)}</td>
        <td><audio controls preload="none" src="../audio/auditions/${encodeURIComponent(file)}"></audio></td>
        <td class="d">Candidate take. Approve it before replacing an indexed cue.</td>
      </tr>`).join('')}
    </table>
  </section>` : '';

const html = `<!doctype html>
<meta charset="utf-8">
<title>Squatch Life - sfx (${files.length})</title>
<style>
  body { font: 14px/1.5 system-ui, sans-serif; margin: 2rem auto; max-width: 60rem; padding: 0 1rem;
         background: #14120f; color: #e8e2d6; }
  h1 { font-size: 1.4rem; }
  h2 { margin: 2rem 0 .5rem; font-size: 1rem; text-transform: uppercase; letter-spacing: .08em; color: #d9a441; }
  .auditions h2 { color: #75b8d8; }
  h2 small { color: #7a7266; font-weight: 400; letter-spacing: 0; text-transform: none; }
  table { border-collapse: collapse; width: 100%; }
  tr { border-bottom: 1px solid #2a2620; }
  td { padding: .3rem .6rem .3rem 0; vertical-align: middle; }
  td.n { font-family: ui-monospace, monospace; white-space: nowrap; color: #c8c0b2; }
  td.d { color: #8b8375; font-size: .85rem; }
  audio { height: 32px; width: 260px; }
</style>
<h1>Squatch Life &mdash; ${files.length} cues</h1>
<p><small>Generated by tools/sfx-index.mjs. Regenerate after <code>npm run sfx</code>.</small></p>
${rows}
${auditionRows}
`;

const dest = path.join(SFX_DIR, '_listen.html');
await fs.writeFile(dest, html);
console.log(`Wrote ${path.relative(ROOT, dest)} (${files.length} cues, ${groups.size} groups).`);

const indexed = await writeIndex(SFX_DIR);
console.log(`Wrote assets/sfx/index.json (${indexed.length} file(s)) — this is what the game fetches.`);
