#!/usr/bin/env node
/**
 * VOICE-LINES-NEEDED.md — what is actually left to record, and nothing else.
 *
 *   npm run voice:needed
 *
 * `VOICE-LINES-TODO.md` is the full production handoff and it stays: it
 * carries the coverage snapshot, the delivery workflow, the legacy queue, the
 * unreachable catalogs and the reconciliation notes. That is the right
 * document for the person running audio production. It is a hundred thousand
 * characters long, and it is the wrong document to hand a voice actor who
 * wants to know what to say into a microphone this afternoon.
 *
 * This is that second document. One rule decides everything in it:
 *
 *     IF A LINE IS IN THE GAME AND HAS NO RECORDING, IT IS HERE.
 *     IF IT DOES NOT NEED SAYING, IT IS NOT.
 *
 * So: no legacy WAV paths, no unreachable catalogs, no sound effects, no
 * "indexed files with no manifest owner", no counts of things that are
 * already done. Every row is a filename, a person, and a sentence.
 *
 * GROUPED BY CHARACTER, not by scene, because that is how the work is done --
 * one voice, one session, one setting on the desk. A voice actor recording
 * Big Uncle Lou does not want his fourteen lines spread across nine scene
 * headings.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = path.join(ROOT, 'assets/sfx/manifest.json');
const INDEX = path.join(ROOT, 'assets/sfx/index.json');
const OUT = path.join(ROOT, 'VOICE-LINES-NEEDED.md');

/** Which scene a cue belongs to, for the note beside each line. */
const SCENES = [
  ['PROJECT SILENT SQUATCH', (n) => n.startsWith('vo.silentsquatch.')],
  ['The HotDog Incident', (n) => n.startsWith('vo.bing2.')],
  ['The Enola Squatch', (n) => n.startsWith('vo.enolasquatch.')],
  ['THE TAKE', (n) => n.startsWith('heist.')],
  ['Bada Bing', (n) => n.startsWith('vo.bing.') || n.startsWith('vo.bj.') || n.startsWith('vo.slots.')],
  ['Silver Pines', (n) => n.startsWith('vo.golf.')],
  ['The Silver Room', (n) => n.startsWith('vo.silver.')],
  ['The Silver Case', (n) => n.startsWith('vo.silvercase.')],
  ['NO WAKE', (n) => n.startsWith('vo.nowake.')],
  ['The Beef Run', (n) => n.startsWith('vo.beefrun.')],
  ['Jerky Motel', (n) => n.startsWith('vo.motel.')],
  ['Squatch Graveyard', (n) => n.startsWith('vo.graveyard.')],
  ['Squatchfather', (n) => n.startsWith('vo.sf.')],
  ['Initiation', (n) => n.startsWith('vo.initiation.')],
  ['Radio', (n) => n.startsWith('radio.')],
  ['Apartment', (n) => n.startsWith('vo.door.') || n.startsWith('vo.call.')
    || n.startsWith('vo.machine.') || n.startsWith('vo.news.') || n.startsWith('vo.idle')],
];

const sceneOf = (name) => SCENES.find(([, owns]) => owns(name))?.[0] || 'Apartment and shared';
const fileOf = (cue) => `${cue.file || cue.name}.mp3`;

/**
 * The Initiation party catalog is authored but unreachable in the playable
 * scene, and the production sheet excludes it from the line run for that
 * reason. Excluded here too: this file is what needs SAYING, and nobody hears
 * these.
 */
const unreachable = (name) => name.startsWith('vo.initiation.party.');

function main() {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  const index = JSON.parse(fs.readFileSync(INDEX, 'utf8'));
  const have = new Set(index.files || []);
  const voices = manifest.voices || {};

  const spoken = (manifest.sfx || [])
    .filter((cue) => typeof cue.say === 'string' && cue.say.trim())
    .filter((cue) => !unreachable(cue.name));

  /* Recast invalidates everything already recorded for that profile: the
   * takes on disk are a different actor. See `recastProfiles` in
   * tools/audio-todo-lib.mjs. */
  const recast = new Map(Object.entries(voices)
    .filter(([, v]) => v && typeof v === 'object' && v.recast)
    .map(([k, v]) => [k, v.recast]));

  const needed = spoken.filter((cue) => !have.has(fileOf(cue))
    || cue.needsRerecord === true
    || recast.has(cue.voice));

  /* One block per voice. A voice actor works a character at a time. */
  const byVoice = new Map();
  for (const cue of needed) {
    const key = cue.voice || '(uncast)';
    if (!byVoice.has(key)) byVoice.set(key, []);
    byVoice.get(key).push(cue);
  }

  const uncast = [...new Set(needed.filter((c) => !voices[c.voice]?.id).map((c) => c.voice))];

  const out = [];
  const total = needed.length;
  const doneCount = spoken.length - needed.length;

  out.push('# Voice lines needed');
  out.push('');
  out.push(`**${total} lines to record.** ${doneCount} of ${spoken.length} are already done.`);
  out.push('');
  out.push('Generated by `npm run voice:needed`. Do not hand-edit — fix the authored line and regenerate.');
  out.push('');
  out.push('One rule decides what is in this file: **if a line is in the game and has no recording, it is here.**');
  out.push('No sound effects, no legacy paths, no unreachable catalogs, no lists of things already finished.');
  out.push('For the full production picture — coverage, delivery workflow, the legacy queue — see `VOICE-LINES-TODO.md`.');
  out.push('');
  out.push('## How to deliver');
  out.push('');
  out.push('Record each line and deliver it under **the exact filename shown**. Drop the files in `assets/sfx/`,');
  out.push('then run `npm run sfx:listen` to rebuild the index and `npm run voice:needed` to see what is left.');
  out.push('');

  if (uncast.length) {
    out.push('## ⚠ Blocked — no voice id');
    out.push('');
    out.push('These profiles have lines waiting and **no ElevenLabs id in the manifest**, so nothing can be');
    out.push('rendered for them. The owner supplies the id, then these unblock.');
    out.push('');
    for (const v of uncast.sort()) {
      const n = byVoice.get(v)?.length ?? 0;
      out.push(`- \`${v}\` — ${n} line${n === 1 ? '' : 's'} waiting`);
    }
    out.push('');
  }

  /* PROFILES THAT ARE THE SAME PERSON.
   *
   * `lou` and `lou1` carry the SAME ElevenLabs id: one man, two cadences --
   * Big Uncle Lou on the phone versus in the room. Printed as two blocks
   * because they are two settings on the desk, but a voice actor looking at
   * three profiles with "lou" in the name needs telling which of them are the
   * same throat before he books three sessions. Derived from the ids, so it
   * cannot go stale the way a hand-written note would. */
  const sameVoice = new Map();
  for (const v of byVoice.keys()) {
    const id = voices[v]?.id;
    if (!id) continue;
    if (!sameVoice.has(id)) sameVoice.set(id, []);
    sameVoice.get(id).push(v);
  }
  const shared = [...sameVoice.values()].filter((list) => list.length > 1);
  if (shared.length) {
    out.push('## Same voice, different setting');
    out.push('');
    out.push('These profiles share one voice id — the same performer, recorded differently.');
    out.push('They are listed separately below because the delivery differs, not the person.');
    out.push('');
    for (const list of shared) {
      out.push(`- ${list.map((v) => `\`${v}\``).join(' and ')} — one voice`);
    }
    out.push('');
  }

  if (recast.size) {
    out.push('## ♻ Recast — re-record everything for these');
    out.push('');
    for (const [profile, info] of recast) {
      out.push(`- \`${profile}\` — recast${info.on ? ` on ${info.on}` : ''}. `
        + 'Every existing take is the previous actor. '
        + `Re-render with \`npm run sfx -- --force --cast ${profile}\`.`);
    }
    out.push('');
  }

  /* Biggest blocks first: that is the order somebody books a session in. */
  const order = [...byVoice.entries()].sort((a, b) => b[1].length - a[1].length);

  out.push('## The lines');
  out.push('');
  out.push('| Character | Lines |');
  out.push('|---|---:|');
  for (const [voice, cues] of order) out.push(`| ${voice} | ${cues.length} |`);
  out.push('');

  for (const [voice, cues] of order) {
    const profile = voices[voice];
    out.push(`### ${voice.replace(/-/g, ' ').toUpperCase()} — ${cues.length} line${cues.length === 1 ? '' : 's'}`);
    out.push('');
    if (!profile?.id) {
      out.push('> **No voice id yet.** These cannot be rendered until the owner supplies one.');
      out.push('');
    } else if (profile._note) {
      out.push(`*${String(profile._note).trim()}*`);
      out.push('');
    }
    /* Grouped by scene inside the character, so a session runs in story order
     * rather than jumping between rooms. */
    const byScene = new Map();
    for (const cue of cues) {
      const scene = sceneOf(cue.name);
      if (!byScene.has(scene)) byScene.set(scene, []);
      byScene.get(scene).push(cue);
    }
    for (const [scene, list] of byScene) {
      out.push(`**${scene}** (${list.length})`);
      out.push('');
      for (const cue of [...list].sort((a, b) => a.name.localeCompare(b.name))) {
        const direction = cue.direction ? ` — *${String(cue.direction).trim()}*` : '';
        const redo = (cue.needsRerecord || recast.has(cue.voice)) ? ' **[RE-RECORD]**' : '';
        out.push(`- \`${fileOf(cue)}\`${redo}`);
        out.push(`  > ${cue.say.trim()}${direction}`);
      }
      out.push('');
    }
  }

  const text = `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (current.replace(/\r\n?/g, '\n') !== text) {
      console.error('VOICE-LINES-NEEDED.md is stale. Run `npm run voice:needed`.');
      process.exitCode = 1;
    } else {
      console.log(`VOICE-LINES-NEEDED.md is up to date (${total} lines outstanding).`);
    }
    return;
  }
  fs.writeFileSync(OUT, text);
  console.log(`Wrote VOICE-LINES-NEEDED.md — ${total} lines to record across ${byVoice.size} voices.`);
  if (uncast.length) console.log(`  BLOCKED, no voice id: ${uncast.join(', ')}`);
}

main();
